<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-BM24KA3" failures="1" tests="7" name="PersonalLoan" time="0.123" errors="0" timestamp="2024-03-04T12:57:37 IST">
  <testcase classname="test.Day1" name="demo" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Day1.demo(Day1.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase classname="test.Day2" name="ThirdTest" time="0.003"/>
  <testcase classname="test.Day2" name="exDataPro" time="0.011"/>
  <testcase classname="test.Day2" name="exDataPro" time="0.002"/>
  <testcase classname="test.Day2" name="exDataPro" time="0.003"/>
  <testcase classname="test.Day4" name="webLogin" time="0.002"/>
  <testcase classname="test.Day4" name="APILogin" time="0.003"/>
  <testcase classname="test.Day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
  <testcase classname="test.Day4" name="MoblieLogin" time="0.0">
    <ignored/>
  </testcase> <!-- MoblieLogin -->
</testsuite> <!-- PersonalLoan -->
